export const VALIDATOR_TYPE_REQUIRE = 'REQUIRE';
export const VALIDATOR_TYPE_MINLENGTH = 'MINLENGTH';
export const VALIDATOR_TYPE_MAXLENGTH = 'MAXLENGTH';
export const VALIDATOR_TYPE_MIN = 'MIN';
export const VALIDATOR_TYPE_MAX = 'MAX';
export const VALIDATOR_TYPE_EMAIL = 'EMAIL';
export const VALIDATOR_TYPE_FILE = 'FILE';

//INPUT COMPONENT
export const INPUT__CHANGE="INPUT__CHANGE";
export const TOUCH_INPUT="TOUCH_INPUT";

//FORM_HOOK
export const SET_DATA_INPUT_HOOK="SET_DATA_INPUT_HOOK";
export const CHANGE_DATA_INPUT_HOOK="CAHNGE_DATA_INPUT_HOOK";